apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/libvirt-log-filters: "2:qemu.qemu_monitor 3:*"
  labels:
    special: vmi-logging-test
  name: vmi-logging-test
spec:
  terminationGracePeriodSeconds: 0
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    resources:
      requests:
        memory: 512Mi
  volumes:
  - containerDisk:
      image: quay.io/kubevirt/cirros-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: cirros
        chpasswd: { expire: False }
    name: cloudinitdisk
