apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: teelogger-test
  labels:
    app: teelogger-test
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: teelogger-test
    spec:
      domain:
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 512Mi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: cirros
            chpasswd: { expire: False }
            ssh_pwauth: True
