apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm-simple
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm-simple
    spec:
      terminationGracePeriodSeconds: 0
      domain:
        resources:
          requests:
            memory: 512Mi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
      - name: cloudinitdisk
        cloudInitNoCloud:
          userDataBase64: SGkuXG4=
