# KubeVirt MCP Configuration
# Defines the order and sources for kubeconfig detection

kubeconfig:
  # Priority order - first match wins
  sources:
    - type: "env_var"
      name: "KUBECONFIG"
      description: "Standard kubectl environment variable"
    
    - type: "env_var" 
      name: "GLOBAL_KUBECONFIG"
      description: "Global kubeconfig for development environments"
    
    - type: "file"
      path: "~/.kube/config"
      description: "Default kubectl config location"

# Optional: timeout for kubectl connectivity tests (seconds)
connectivity_test:
  timeout: 10
  command: ["kubectl", "get", "nodes"]

# Optional: logging configuration
logging:
  level: "info"  # debug, info, warn, error
